### ISSUE TITLE
Outdated version in Ansible galaxy

### ISSUE THREAD

**Issue by Nklya** [Stouts/Stouts.iptables#14]
Hello.

Please update version in Ansible galaxy to latest version, from 1.1.1 → 1.1.2
https://galaxy.ansible.com/Stouts/iptables/

**Comment by jtreminio** [comment]
For now, this works:

```- src: Stouts.iptables
  src: https://github.com/Stouts/Stouts.iptables
  version: 1.1.3```

**Comment by Nklya** [comment]
I know that it works that way.
BTW, the same version in galaxy would be better.

**Comment by Nklya** [comment]
OK, it seems that nobody cares about it.
I close it.
