### ISSUE TITLE
Incorrect link in badge to Ansible galaxy

### ISSUE THREAD

**Issue by Nklya** [Stouts/Stouts.iptables#15]
Hello.

I've found that there is incorrect link  in badge to Ansible galaxy.

Now:
> https://galaxy.ansible.com/list#/roles/920

Should be:
> https://galaxy.ansible.com/Stouts/iptables 

[![Galaxy](http://img.shields.io/badge/galaxy-Stouts.iptables-blue.svg?style=flat-square)](https://galaxy.ansible.com/Stouts/iptables/)

**Comment by Nklya** [comment]
Ok, seems nobody don't care.

**Comment by kirjastojk** [comment]
I can send pull request for this.
